/**
 * @fileoverview Professional DOCX export with enterprise medical formatting.
 * 
 * This module generates production-quality Microsoft Word documents with:
 * - Professional medical letterhead with Caduceus symbol
 * - Intelligent page break management
 * - Proper table formatting without orphan rows
 * - Enterprise-grade typography and spacing
 * - Medical color scheme and branding
 * 
 * @module utils/exportDOCX
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  Header,
  Footer,
  TableLayoutType,
  convertInchesToTwip,
  ShadingType,
  VerticalAlign,
  PageOrientation
} from 'docx';
import { saveAs } from 'file-saver';
import type { MedicalNote } from '../types';
import type { ExportConfig } from './exportHelpers';
import { MEDICAL_COLORS } from './exportHelpers';

/**
 * Professional DOCX styling constants.
 */
const DOCX_STYLES = {
  fonts: {
    body: 'Calibri',
    heading: 'Calibri',
    medical: 'Calibri'
  },
  sizes: {
    title: 16,
    heading1: 14,
    heading2: 12,
    body: 11,
    small: 9
  },
  spacing: {
    afterTitle: 240,
    afterHeading: 120,
    afterParagraph: 120,
    beforeSection: 240
  },
  margins: {
    top: convertInchesToTwip(1),
    bottom: convertInchesToTwip(1),
    left: convertInchesToTwip(1),
    right: convertInchesToTwip(1)
  }
} as const;

/**
 * Creates a professional medical letterhead with Caduceus symbol.
 */
function createMedicalHeader(_config: ExportConfig): Header {
  return new Header({
    children: [
      // Letterhead with medical branding
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 120 },
        children: [
          new TextRun({
            text: '⚕️ ',
            size: 24,
            color: MEDICAL_COLORS.caduceus
          }),
          new TextRun({
            text: 'DOCSCRIBE MEDICAL DOCUMENTATION',
            font: DOCX_STYLES.fonts.heading,
            size: DOCX_STYLES.sizes.title,
            bold: true,
            color: MEDICAL_COLORS.primary
          })
        ]
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 240 },
        children: [
          new TextRun({
            text: 'AI-Powered Clinical Documentation System',
            font: DOCX_STYLES.fonts.body,
            size: DOCX_STYLES.sizes.small,
            italics: true,
            color: MEDICAL_COLORS.muted
          })
        ]
      })
    ]
  });
}

/**
 * Creates a professional document footer.
 */
function createDocumentFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 120 },
        children: [
          new TextRun({
            text: 'Generated by DocScribe • ',
            font: DOCX_STYLES.fonts.body,
            size: DOCX_STYLES.sizes.small,
            color: MEDICAL_COLORS.muted
          }),
          new TextRun({
            text: new Date().toLocaleDateString(),
            font: DOCX_STYLES.fonts.body,
            size: DOCX_STYLES.sizes.small,
            color: MEDICAL_COLORS.muted
          }),
          new TextRun({
            text: ' • Page ',
            font: DOCX_STYLES.fonts.body,
            size: DOCX_STYLES.sizes.small,
            color: MEDICAL_COLORS.muted
          })
        ]
      })
    ]
  });
}

/**
 * Creates the encounter information table with proper formatting.
 */
function createEncounterInfoTable(note: MedicalNote, config: ExportConfig): Table {
  const rows: TableRow[] = [];

  // Create encounter info rows
  const encounterData = [
    ['Encounter Type', note.encounterType || note.refinedNote.format],
    ['Date & Time', new Date(note.timestamp).toLocaleString()],
    ...(config.clinicName ? [['Clinic', config.clinicName]] : []),
    ...(config.physicianName ? [['Provider', config.physicianName]] : []),
    ['Note ID', note.id]
  ];

  encounterData.forEach(([label, value]) => {
    rows.push(new TableRow({
      children: [
        new TableCell({
          width: { size: 25, type: WidthType.PERCENTAGE },
          shading: { fill: '#F8F9FA', type: ShadingType.SOLID },
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: label,
                  font: DOCX_STYLES.fonts.body,
                  size: DOCX_STYLES.sizes.body,
                  bold: true,
                  color: MEDICAL_COLORS.text
                })
              ]
            })
          ]
        }),
        new TableCell({
          width: { size: 75, type: WidthType.PERCENTAGE },
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: value,
                  font: DOCX_STYLES.fonts.body,
                  size: DOCX_STYLES.sizes.body,
                  color: MEDICAL_COLORS.text
                })
              ]
            })
          ]
        })
      ]
    }));
  });

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    layout: TableLayoutType.FIXED,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.muted },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.muted },
      left: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.muted },
      right: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.muted },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: '#E9ECEF' },
      insideVertical: { style: BorderStyle.SINGLE, size: 1, color: '#E9ECEF' }
    },
    rows
  });
}

/**
 * Creates the clinical summary table with intelligent formatting.
 */
function createClinicalSummaryTable(note: MedicalNote): Table {
  const rows: TableRow[] = [];
  const summary = note.clinicalSummary;

  const summaryData = [
    ...(summary.chiefComplaint ? [['Chief Complaint', summary.chiefComplaint]] : []),
    ...(summary.keyFindings ? [['Key Findings', summary.keyFindings]] : []),
    ...(summary.plan ? [['Plan', summary.plan]] : []),
    ...(summary.followUp ? [['Follow-up', summary.followUp]] : [])
  ];

  summaryData.forEach(([label, content]) => {
    rows.push(new TableRow({
      children: [
        new TableCell({
          width: { size: 20, type: WidthType.PERCENTAGE },
          shading: { fill: '#E3F2FD', type: ShadingType.SOLID },
          verticalAlign: VerticalAlign.TOP,
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: label,
                  font: DOCX_STYLES.fonts.body,
                  size: DOCX_STYLES.sizes.body,
                  bold: true,
                  color: MEDICAL_COLORS.primary
                })
              ]
            })
          ]
        }),
        new TableCell({
          width: { size: 80, type: WidthType.PERCENTAGE },
          verticalAlign: VerticalAlign.TOP,
          children: [
            new Paragraph({
              spacing: { after: 0 },
              children: [
                new TextRun({
                  text: content,
                  font: DOCX_STYLES.fonts.body,
                  size: DOCX_STYLES.sizes.body,
                  color: MEDICAL_COLORS.text
                })
              ]
            })
          ]
        })
      ]
    }));
  });

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    layout: TableLayoutType.FIXED,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.primary },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.primary },
      left: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.primary },
      right: { style: BorderStyle.SINGLE, size: 1, color: MEDICAL_COLORS.primary },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: '#BBDEFB' },
      insideVertical: { style: BorderStyle.SINGLE, size: 1, color: '#BBDEFB' }
    },
    rows
  });
}

/**
 * Creates detailed note sections with proper page flow management.
 */
function createDetailedNoteSections(note: MedicalNote): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  note.refinedNote.sections.forEach((section, index) => {
    // Add section heading
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        spacing: { 
          before: index === 0 ? DOCX_STYLES.spacing.beforeSection : DOCX_STYLES.spacing.beforeSection,
          after: DOCX_STYLES.spacing.afterHeading 
        },
        children: [
          new TextRun({
            text: section.heading.toUpperCase(),
            font: DOCX_STYLES.fonts.heading,
            size: DOCX_STYLES.sizes.heading2,
            bold: true,
            color: MEDICAL_COLORS.accent
          })
        ]
      })
    );

    // Split long content into paragraphs for better page flow
    const contentParagraphs = splitContentIntoParagraphs(section.body);
    contentParagraphs.forEach((paragraph, pIndex) => {
      paragraphs.push(
        new Paragraph({
          spacing: { 
            after: pIndex === contentParagraphs.length - 1 ? DOCX_STYLES.spacing.afterParagraph : 60 
          },
          children: [
            new TextRun({
              text: paragraph,
              font: DOCX_STYLES.fonts.body,
              size: DOCX_STYLES.sizes.body,
              color: MEDICAL_COLORS.text
            })
          ]
        })
      );
    });
  });

  return paragraphs;
}

/**
 * Splits long content into logical paragraphs to prevent orphan text.
 */
function splitContentIntoParagraphs(content: string): string[] {
  // Split by sentences, but keep logical groupings together
  const sentences = content.split(/(?<=[.!?])\s+/);
  const paragraphs: string[] = [];
  let currentParagraph = '';
  
  sentences.forEach(sentence => {
    if (currentParagraph.length + sentence.length > 400) {
      if (currentParagraph.trim()) {
        paragraphs.push(currentParagraph.trim());
      }
      currentParagraph = sentence;
    } else {
      currentParagraph += (currentParagraph ? ' ' : '') + sentence;
    }
  });
  
  if (currentParagraph.trim()) {
    paragraphs.push(currentParagraph.trim());
  }
  
  return paragraphs.length > 0 ? paragraphs : [content];
}

/**
 * Creates AI-generated summaries section.
 */
function createAISummariesSection(note: MedicalNote, config: ExportConfig): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  if ((config.includePatientSummary && note.patientSummary) || 
      (config.includeClinicalSummary && note.clinicalSummaryText)) {
    
    // Section header
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: DOCX_STYLES.spacing.beforeSection, after: DOCX_STYLES.spacing.afterHeading },
        children: [
          new TextRun({
            text: 'AI-GENERATED SUMMARIES',
            font: DOCX_STYLES.fonts.heading,
            size: DOCX_STYLES.sizes.heading1,
            bold: true,
            color: MEDICAL_COLORS.secondary
          })
        ]
      })
    );

    // Patient summary
    if (config.includePatientSummary && note.patientSummary) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 180, after: DOCX_STYLES.spacing.afterHeading },
          children: [
            new TextRun({
              text: 'Patient-Friendly Summary',
              font: DOCX_STYLES.fonts.heading,
              size: DOCX_STYLES.sizes.heading2,
              bold: true,
              color: MEDICAL_COLORS.accent
            })
          ]
        })
      );

      const patientParagraphs = splitContentIntoParagraphs(note.patientSummary);
      patientParagraphs.forEach(paragraph => {
        paragraphs.push(
          new Paragraph({
            spacing: { after: DOCX_STYLES.spacing.afterParagraph },
            children: [
              new TextRun({
                text: paragraph,
                font: DOCX_STYLES.fonts.body,
                size: DOCX_STYLES.sizes.body,
                color: MEDICAL_COLORS.text
              })
            ]
          })
        );
      });
    }

    // Clinical summary text
    if (config.includeClinicalSummary && note.clinicalSummaryText) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 180, after: DOCX_STYLES.spacing.afterHeading },
          children: [
            new TextRun({
              text: 'Clinical Summary',
              font: DOCX_STYLES.fonts.heading,
              size: DOCX_STYLES.sizes.heading2,
              bold: true,
              color: MEDICAL_COLORS.accent
            })
          ]
        })
      );

      const clinicalParagraphs = splitContentIntoParagraphs(note.clinicalSummaryText);
      clinicalParagraphs.forEach(paragraph => {
        paragraphs.push(
          new Paragraph({
            spacing: { after: DOCX_STYLES.spacing.afterParagraph },
            children: [
              new TextRun({
                text: paragraph,
                font: DOCX_STYLES.fonts.body,
                size: DOCX_STYLES.sizes.body,
                color: MEDICAL_COLORS.text
              })
            ]
          })
        );
      });
    }
  }

  return paragraphs;
}

/**
 * Creates translation section if available.
 */
function createTranslationSection(note: MedicalNote): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  if (note.translatedSummary && note.targetLanguage) {
    paragraphs.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: DOCX_STYLES.spacing.beforeSection, after: DOCX_STYLES.spacing.afterHeading },
        children: [
          new TextRun({
            text: `TRANSLATED SUMMARY (${note.targetLanguage.toUpperCase()})`,
            font: DOCX_STYLES.fonts.heading,
            size: DOCX_STYLES.sizes.heading1,
            bold: true,
            color: MEDICAL_COLORS.secondary
          })
        ]
      })
    );

    const translatedParagraphs = splitContentIntoParagraphs(note.translatedSummary);
    translatedParagraphs.forEach(paragraph => {
      paragraphs.push(
        new Paragraph({
          spacing: { after: DOCX_STYLES.spacing.afterParagraph },
          children: [
            new TextRun({
              text: paragraph,
              font: DOCX_STYLES.fonts.body,
              size: DOCX_STYLES.sizes.body,
              color: MEDICAL_COLORS.text
            })
          ]
        })
      );
    });
  }

  return paragraphs;
}

/**
 * Exports a medical note as a professional DOCX document.
 * 
 * @param note - The medical note to export
 * @param config - Export configuration options
 * @param filename - The filename for the exported document
 */
export async function exportMedicalNoteDOCX(
  note: MedicalNote, 
  config: ExportConfig, 
  filename: string
): Promise<void> {
  try {
    const doc = new Document({
      styles: {
        default: {
          document: {
            run: {
              font: DOCX_STYLES.fonts.body,
              size: DOCX_STYLES.sizes.body
            }
          }
        }
      },
      sections: [{
        properties: {
          page: {
            margin: DOCX_STYLES.margins,
            size: {
              orientation: PageOrientation.PORTRAIT
            }
          }
        },
        headers: config.includeHeader ? { default: createMedicalHeader(config) } : undefined,
        footers: config.includeTimestamp ? { default: createDocumentFooter() } : undefined,
        children: [
          // Title
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: DOCX_STYLES.spacing.afterTitle },
            children: [
              new TextRun({
                text: `${note.encounterType || note.refinedNote.format} Clinical Note`,
                font: DOCX_STYLES.fonts.heading,
                size: DOCX_STYLES.sizes.title,
                bold: true,
                color: MEDICAL_COLORS.primary
              })
            ]
          }),

          // Encounter Information Table
          createEncounterInfoTable(note, config),

          // Clinical Summary Section
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: DOCX_STYLES.spacing.beforeSection, after: DOCX_STYLES.spacing.afterHeading },
            children: [
              new TextRun({
                text: 'CLINICAL SUMMARY',
                font: DOCX_STYLES.fonts.heading,
                size: DOCX_STYLES.sizes.heading1,
                bold: true,
                color: MEDICAL_COLORS.secondary
              })
            ]
          }),

          createClinicalSummaryTable(note),

          // Detailed Note Sections
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: DOCX_STYLES.spacing.beforeSection, after: DOCX_STYLES.spacing.afterHeading },
            children: [
              new TextRun({
                text: 'DETAILED CLINICAL NOTE',
                font: DOCX_STYLES.fonts.heading,
                size: DOCX_STYLES.sizes.heading1,
                bold: true,
                color: MEDICAL_COLORS.secondary
              })
            ]
          }),

          ...createDetailedNoteSections(note),

          // AI Summaries Section
          ...createAISummariesSection(note, config),

          // Translation Section
          ...createTranslationSection(note)
        ]
      }]
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${filename}.docx`);
    
    console.log(`DOCX export completed: ${filename}.docx`);
    
  } catch (error) {
    console.error('DOCX export failed:', error);
    throw new Error(`Failed to generate DOCX document: ${(error as Error).message}`);
  }
}