/**
 * @fileoverview Core TypeScript interfaces for DocScribe medical documentation.
 *
 * @description
 * This module defines the essential data structures that model the clinical notes
 * and related entities within the DocScribe application. The cornerstone is the
 * {@link MedicalNote} interface, which represents the comprehensive output
 * generated by the AI from a user's dictation.
 *
 * @module types
 */

/**
 * Represents the format type of a clinical note.
 * The AI model is prompted to automatically detect which format best matches the dictated content.
 */
export type NoteFormat =
  | 'SOAP'
  | 'Progress'
  | 'Discharge'
  | 'Conference'
  | 'Consultation'
  | 'Procedure'
  | 'Unknown';

/**
 * Represents the role of a speaker detected in the medical transcript.
 * Expanded to support encounter-specific speaker identification.
 */
export type SpeakerRole = 
  | 'Provider'        // Primary attending physician, surgeon, specialist
  | 'Patient'         // The individual receiving care
  | 'Nurse'           // RN, LPN, charge nurse, scrub nurse
  | 'Anesthesiologist' // Anesthesia provider, CRNA
  | 'Resident'        // Medical resident, intern, fellow
  | 'Student'         // Medical student, nursing student
  | 'Technician'      // Surgical tech, radiology tech, lab tech
  | 'Family'          // Spouse, children, parents, significant others
  | 'Specialist'      // Consulting physician (different from primary Provider)
  | 'Paramedic'       // EMS personnel giving report
  | 'Other'           // Other healthcare personnel
  | 'Unknown';        // Use only if truly ambiguous even with context

/**
 * Represents a single segment of transcribed speech with speaker identification.
 */
export interface TranscriptSegment {
  speaker: SpeakerRole;
  text: string;
}

/**
 * Represents a section of a structured medical note.
 */
export interface NoteSection {
  heading: string;
  body: string;
}

/**
 * Represents the refined, structured medical note with formatted sections.
 */
export interface RefinedNote {
  format: NoteFormat;
  sections: NoteSection[];
}

/**
 * Represents a concise clinical summary extracted from the medical note.
 */
export interface ClinicalSummary {
  chiefComplaint: string;
  keyFindings: string;
  plan: string;
  followUp: string;
}

/**
 * The complete medical note structure generated by the AI.
 * Enhanced with Summarizer and Translator API capabilities.
 */
export interface MedicalNote {
  id: string;
  timestamp: string;
  encounterType?: NoteFormat;
  rawTranscript: string;
  cleanedTranscript: string;
  labeledTranscript: TranscriptSegment[];
  refinedNote: RefinedNote;
  clinicalSummary: ClinicalSummary;
  
  // AI-enhanced summaries from Summarizer API
  patientSummary?: string;           // Patient-friendly summary using Summarizer API
  clinicalSummaryText?: string;      // Clinical summary for healthcare providers
  
  // Translation support from Translator API
  translatedSummary?: string;        // Translated patient summary
  targetLanguage?: string;           // Target language for translations
  
  // Processing metadata
  aiProcessingTime?: number;         // Time taken for AI enhancement in milliseconds
}
