/**
 * @fileoverview Core TypeScript interfaces for DocScribe medical documentation.
 * 
 * This module defines the data structures for clinical notes generated by the AI.
 * The MedicalNote interface represents the three-part output structure returned
 * by the Chrome Prompt API: raw transcript with speaker detection, refined 
 * formatted note, and clinical summary.
 *
 * CRITICAL: Speaker diarization is inferred by the AI from context, not detected
 * by hardware. Gemini Nano does not support true speaker diarization.
 *
 * @module types
 */

/**
 * Represents the format type of a clinical note.
 * The AI will automatically detect which format best matches the dictated content.
 */
export type NoteFormat = 
  | 'SOAP' 
  | 'Progress' 
  | 'Discharge' 
  | 'Conference' 
  | 'Consultation'
  | 'Procedure'
  | 'Unknown';

/**
 * Represents a detected speaker in the conversation.
 * Inferred by AI from context, not true diarization.
 */
export type SpeakerRole = 
  | 'Provider' 
  | 'Patient' 
  | 'Nurse' 
  | 'Family' 
  | 'Unknown';

/**
 * Represents a single utterance in the conversation with speaker attribution.
 */
export interface TranscriptSegment {
  /**
   * The inferred speaker role for this segment.
   */
  speaker: SpeakerRole;

  /**
   * The verbatim text spoken by this speaker.
   */
  text: string;

  /**
   * Optional timestamp in seconds from the start of recording.
   */
  timestamp?: number;
}

/**
 * Represents a single section within a clinical note.
 * Used to structure the refined note into logical parts with headers.
 */
export interface NoteSection {
  /**
   * The section header (e.g., "Subjective", "Assessment and Plan").
   */
  title: string;

  /**
   * The section content with all medical details preserved.
   */
  body: string;
}

/**
 * Represents the refined, formatted clinical note output.
 * This is the professionally formatted version with cleaned grammar,
 * proper structure, and medical terminology preserved.
 */
export interface RefinedNote {
  /**
   * The detected note format type.
   */
  format: NoteFormat;

  /**
   * The full formatted note content as a single string.
   */
  content: string;

  /**
   * The note broken into structured sections for easier navigation.
   */
  sections: NoteSection[];
}

/**
 * Represents a concise clinical summary extracted from the full note.
 * This provides quick reference to the most critical information.
 */
export interface ClinicalSummary {
  /**
   * The primary reason for the patient visit or concern.
   */
  chiefComplaint: string;

  /**
   * Key clinical findings, diagnoses, or test results.
   */
  keyFindings: string;

  /**
   * The treatment plan or next steps for the patient.
   */
  plan: string;

  /**
   * Optional follow-up instructions or timeline.
   */
  followUp?: string;
}

/**
 * Represents a complete medical note with all three output sections.
 * This is the primary data structure returned by the AI transcription service
 * and stored in the application state.
 *
 * WORKFLOW:
 * 1. Audio input → Raw transcript with inferred speakers
 * 2. Raw transcript → Refined note (cleaned and structured)
 * 3. Raw transcript → Clinical summary (key points)
 *
 * @example
 * ```
 * const note: MedicalNote = {
 *   id: "550e8400-e29b-41d4-a716-446655440000",
 *   timestamp: "2025-10-21T10:00:00.000Z",
 *   rawTranscript: [
 *     { speaker: "Provider", text: "What brings you in today?" },
 *     { speaker: "Patient", text: "I've been having chest pain for two days." }
 *   ],
 *   refinedNote: {
 *     format: "SOAP",
 *     content: "Patient is a 45-year-old male presenting with...",
 *     sections: [
 *       { title: "Subjective", body: "Patient reports chest pain..." },
 *       { title: "Objective", body: "Vital signs: BP 120/80..." }
 *     ]
 *   },
 *   clinicalSummary: {
 *     chiefComplaint: "Chest pain for 2 days",
 *     keyFindings: "EKG normal, troponin negative",
 *     plan: "Discharge with nitroglycerin PRN, follow up in 1 week"
 *   }
 * };
 * ```
 */
export interface MedicalNote {
  /**
   * Unique identifier for the note (UUID v4).
   */
  id: string;

  /**
   * ISO 8601 timestamp of when this note was created.
   */
  timestamp: string;

  /**
   * The verbatim transcription of the audio dictation with speaker attribution.
   * Speakers are inferred by AI from conversational context, not true diarization.
   * Includes all words spoken, including filler words and false starts.
   */
  rawTranscript: TranscriptSegment[];

  /**
   * The professionally formatted clinical note with cleaned grammar
   * and proper structure while preserving all medical details.
   */
  refinedNote: RefinedNote;

  /**
   * A concise summary of the most critical clinical information.
   */
  clinicalSummary: ClinicalSummary;

  /**
   * Optional audio blob for playback or re-processing.
   * Not persisted to LocalStorage due to size constraints.
   */
  audioBlob?: Blob;
}

/**
 * Represents the availability status of the Chrome AI model.
 */
export type AIAvailability = 
  | 'available' 
  | 'downloadable' 
  | 'downloading' 
  | 'unavailable';

/**
 * Configuration options for AI session creation.
 */
export interface AISessionConfig {
  /**
   * Output language code (en, es, or ja).
   */
  outputLanguage: 'en' | 'es' | 'ja';

  /**
   * System prompt to guide AI behavior.
   */
  systemPrompt: string;

  /**
   * Temperature for response randomness (0.0 to 1.0).
   * Lower values are more deterministic.
   */
  temperature?: number;

  /**
   * Top-K sampling parameter.
   */
  topK?: number;
}
