/**
 * @fileoverview Core TypeScript interfaces for DocScribe medical documentation.
 *
 * @description
 * This module defines the essential data structures that model the clinical notes
 * and related entities within the DocScribe application. The cornerstone is the
 * {@link MedicalNote} interface, which represents the comprehensive three-part output
 * generated by the AI from a user's dictation, now including optional translations.
 *
 * @module types
 */

/**
 * Represents the format type of a clinical note.
 * The AI model is prompted to automatically detect which format best matches the dictated content.
 */
export type NoteFormat =
  | 'SOAP'          // Subjective, Objective, Assessment, Plan
  | 'Progress'      // Standard progress note
  | 'Discharge'     // Discharge summary
  | 'Conference'    // Case conference notes
  | 'Consultation'  // Specialist consultation report
  | 'Procedure'     // Note detailing a medical procedure
  | 'Unknown';      // Format could not be determined

/**
 * Represents a detected speaker in the conversation.
 * This is a more specific type for structured transcript segments.
 */
export type SpeakerRole = 'Provider' | 'Patient' | 'Nurse' | 'Other';

/**
 * Represents a single, contiguous utterance in the conversation with its attributed speaker and timing information.
 */
export interface TranscriptSegment {
  /**
   * The role of the speaker for this segment of text.
   */
  speaker: SpeakerRole;

  /**
   * The verbatim text spoken by the speaker in this segment.
   */
  text: string;

  /**
   * An optional formatted timestamp string indicating when this segment started.
   * @example "00:01:23"
   * @type {string | undefined}
   */
  timestamp?: string;

  /**
   * An optional timestamp in milliseconds from the start of the recording.
   * This is useful for programmatic audio seeking.
   * @type {number | undefined}
   */
  startTime?: number;
}

/**
 * Represents a single, titled section within a structured clinical note.
 */
export interface NoteSection {
  /**
   * The title or header for the section (e.g., "Subjective", "History of Present Illness").
   */
  title: string;

  /**
   * The detailed content of the section, typically formatted as a paragraph or list.
   */
  body: string;
}

/**
 * Represents the refined, professionally formatted clinical note, with optional translations.
 */
export interface RefinedNote {
  /**
   * The clinical format that the AI determined for the note (e.g., 'SOAP').
   */
  format: NoteFormat;

  /**
   * The complete, formatted note content in its original language as a single string.
   */
  content: string;

  /**
   * The note's content broken down into structured sections in the original language.
   */
  sections: NoteSection[];

  /**
   * An optional translation of the complete, formatted note content.
   * @type {string | undefined}
   */
  translatedContent?: string;

  /**
   * An optional translation of the note's structured sections.
   * @type {NoteSection[] | undefined}
   */
  translatedSections?: NoteSection[];
}

/**
 * Represents a concise, high-level summary of the clinical encounter, with optional translations.
 */
export interface ClinicalSummary {
  /**
   * The primary reason for the patient's visit in the original language.
   */
  chiefComplaint: string;

  /**
   * A brief summary of the most important clinical findings in the original language.
   */
  keyFindings: string;

  /**
   * The proposed treatment plan in the original language.
   */
  plan: string;

  /**
   * Optional follow-up instructions in the original language.
   * @type {string | undefined}
   */
  followUp?: string;

  /**
   * An optional translation of the chief complaint.
   * @type {string | undefined}
   */
  translatedChiefComplaint?: string;

  /**
   * An optional translation of the key findings.
   * @type {string | undefined}
   */
  translatedKeyFindings?: string;

  /**
   * An optional translation of the treatment plan.
   * @type {string | undefined}
   */
  translatedPlan?: string;

  /**
   * An optional translation of the follow-up instructions.
   * @type {string | undefined}
   */
  translatedFollowUp?: string;
}

/**
 * Represents a complete medical note, encapsulating all AI-generated outputs and their translations.
 * This is the primary data structure used throughout the application.
 */
export interface MedicalNote {
  /**
   * A unique identifier for the note, typically a UUID v4.
   */
  id: string;

  /**
   * The ISO 8601 timestamp indicating when this note was created.
   */
  timestamp: string;

  /**
   * The original, immutable, verbatim transcription of the audio dictation, with speaker and timing information.
   */
  rawTranscript: TranscriptSegment[];

  /**
   * An optional translation of the verbatim transcript.
   * @type {TranscriptSegment[] | undefined}
   */
  translatedTranscript?: TranscriptSegment[];

  /**
   * The professionally formatted clinical note, including optional translations.
   */
  refinedNote: RefinedNote;

  /**
   * A concise summary of the clinical encounter, including optional translations.
   */
  clinicalSummary: ClinicalSummary;

  /**
   * The ISO 639-1 code of the language into which the note has been translated (e.g., "es", "fr").
   * This field is present if any part of the note has been translated.
   * @type {string | undefined}
   */
  translationLanguage?: string;

  /**
   * The original audio recording as a Blob object.
   * This is not persisted to LocalStorage due to its size but is available in the session.
   */
  audioBlob: Blob;
}

/**
 * Represents the availability status of the on-device Chrome AI model.
 */
export type AIAvailability =
  | 'readily'
  | 'after-download'
  | 'no';

/**
 * Defines the configuration options for creating a new AI text session.
 */
export interface AISessionConfig {
  /**
   * The target language for the AI's output.
   */
  outputLanguage: 'en' | 'es' | 'ja';

  /**
   * The system prompt used to instruct the AI on its role and task.
   */
  systemPrompt: string;

  /**
   * Controls the randomness of the AI's output (0.0 to 1.0).
   */
  temperature?: number;

  /**
   * The Top-K sampling parameter.
   */
  topK?: number;
}
