/**
 * @fileoverview Professional PDF export with enterprise medical formatting.
 * 
 * This module generates production-quality PDF documents with:
 * - Professional medical letterhead with Caduceus symbol
 * - Intelligent table formatting and page breaks
 * - Medical color scheme and branding
 * - Proper typography and spacing
 * - Auto-generated table of contents
 * - Page numbering and footers
 * 
 * @module utils/exportPDF
 */

import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { saveAs } from 'file-saver';
import type { MedicalNote } from '../types';
import type { ExportConfig } from './exportHelpers';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

/**
 * Professional PDF styling constants.
 */
const PDF_STYLES = {
  fonts: {
    body: 'helvetica',
    heading: 'helvetica',
    medical: 'helvetica'
  },
  sizes: {
    title: 18,
    heading1: 14,
    heading2: 12,
    body: 10,
    small: 8,
    tiny: 7
  },
  margins: {
    top: 20 as number,
    bottom: 20 as number,
    left: 20 as number,
    right: 20 as number
  },
  spacing: {
    lineHeight: 1.4,
    sectionSpacing: 8,
    paragraphSpacing: 4
  },
  colors: {
    primary: '#0066CC',
    secondary: '#2E7D32',
    accent: '#1565C0',
    text: '#212529',
    muted: '#6C757D',
    light: '#F8F9FA',
    border: '#DEE2E6'
  }
} as const;

/**
 * PDF page layout configuration.
 */
const PAGE_CONFIG = {
  format: 'a4' as const,
  width: 210,
  height: 297,
  usableWidth: 170, // Accounting for margins
  usableHeight: 257  // Accounting for margins and headers/footers
};

/**
 * Draws the professional medical header with Caduceus symbol.
 */
function drawMedicalHeader(doc: jsPDF, _config: ExportConfig): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = PDF_STYLES.margins.top;

  // Draw header background
  doc.setFillColor(PDF_STYLES.colors.light);
  doc.rect(0, 0, pageWidth, 35, 'F');

  // Medical symbol (Caduceus)
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(24);
  doc.setTextColor(PDF_STYLES.colors.primary);
  doc.text('⚕', pageWidth / 2 - 5, yPos + 8, { align: 'center' });

  // Main title
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(PDF_STYLES.sizes.title);
  doc.setTextColor(PDF_STYLES.colors.primary);
  doc.text('DOCSCRIBE MEDICAL DOCUMENTATION', pageWidth / 2, yPos + 18, { align: 'center' });

  // Subtitle
  doc.setFont(PDF_STYLES.fonts.body, 'italic');
  doc.setFontSize(PDF_STYLES.sizes.small);
  doc.setTextColor(PDF_STYLES.colors.muted);
  doc.text('AI-Powered Clinical Documentation System', pageWidth / 2, yPos + 25, { align: 'center' });

  // Border line
  doc.setDrawColor(PDF_STYLES.colors.primary);
  doc.setLineWidth(0.5);
  doc.line(PDF_STYLES.margins.left, yPos + 30, pageWidth - PDF_STYLES.margins.right, yPos + 30);

  return yPos + 40;
}

/**
 * Draws the professional footer with page numbers.
 */
function drawFooter(doc: jsPDF, pageNumber: number, totalPages: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 15;

  // Footer line
  doc.setDrawColor(PDF_STYLES.colors.border);
  doc.setLineWidth(0.25);
  doc.line(PDF_STYLES.margins.left, footerY - 5, pageWidth - PDF_STYLES.margins.right, footerY - 5);

  // Left side: Generation info
  doc.setFont(PDF_STYLES.fonts.body, 'normal');
  doc.setFontSize(PDF_STYLES.sizes.tiny);
  doc.setTextColor(PDF_STYLES.colors.muted);
  doc.text(`Generated by DocScribe • ${new Date().toLocaleDateString()}`, PDF_STYLES.margins.left, footerY);

  // Right side: Page numbers
  doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - PDF_STYLES.margins.right, footerY, { align: 'right' });
}

/**
 * Adds encounter information table.
 */
function addEncounterInfoTable(doc: jsPDF, note: MedicalNote, config: ExportConfig, startY: number): number {
  const encounterData = [
    ['Encounter Type', note.encounterType || note.refinedNote.format],
    ['Date & Time', new Date(note.timestamp).toLocaleString()],
    ...(config.clinicName ? [['Clinic', config.clinicName]] : []),
    ...(config.physicianName ? [['Provider', config.physicianName]] : []),
    ['Note ID', note.id]
  ];

  doc.autoTable({
    startY: startY,
    head: [['Field', 'Value']],
    body: encounterData,
    theme: 'grid',
    styles: {
      fontSize: PDF_STYLES.sizes.body,
      cellPadding: 3,
      lineColor: PDF_STYLES.colors.border,
      lineWidth: 0.1
    },
    headStyles: {
      fillColor: PDF_STYLES.colors.primary,
      textColor: '#FFFFFF',
      fontStyle: 'bold',
      fontSize: PDF_STYLES.sizes.body
    },
    columnStyles: {
      0: { 
        cellWidth: 40,
        fillColor: PDF_STYLES.colors.light,
        fontStyle: 'bold'
      },
      1: { 
        cellWidth: 130,
        fontStyle: 'normal'
      }
    },
    margin: { left: PDF_STYLES.margins.left, right: PDF_STYLES.margins.right },
    tableWidth: 'wrap'
  });

  return (doc as any).lastAutoTable.finalY + PDF_STYLES.spacing.sectionSpacing;
}

/**
 * Adds clinical summary section with professional formatting.
 */
function addClinicalSummarySection(doc: jsPDF, note: MedicalNote, startY: number): number {
  let yPos = startY;

  // Section heading
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(PDF_STYLES.sizes.heading1);
  doc.setTextColor(PDF_STYLES.colors.secondary);
  doc.text('CLINICAL SUMMARY', PDF_STYLES.margins.left, yPos);
  yPos += PDF_STYLES.spacing.sectionSpacing;

  // Clinical summary table
  const summaryData: string[][] = [];
  const summary = note.clinicalSummary;

  if (summary.chiefComplaint) {
    summaryData.push(['Chief Complaint', summary.chiefComplaint]);
  }
  if (summary.keyFindings) {
    summaryData.push(['Key Findings', summary.keyFindings]);
  }
  if (summary.plan) {
    summaryData.push(['Plan', summary.plan]);
  }
  if (summary.followUp) {
    summaryData.push(['Follow-up', summary.followUp]);
  }

  if (summaryData.length > 0) {
    doc.autoTable({
      startY: yPos,
      body: summaryData,
      theme: 'grid',
      styles: {
        fontSize: PDF_STYLES.sizes.body,
        cellPadding: 4,
        lineColor: PDF_STYLES.colors.border,
        lineWidth: 0.1,
        overflow: 'linebreak'
      },
      columnStyles: {
        0: { 
          cellWidth: 35,
          fillColor: '#E3F2FD',
          fontStyle: 'bold',
          textColor: PDF_STYLES.colors.primary,
          valign: 'top'
        },
        1: { 
          cellWidth: 135,
          fontStyle: 'normal',
          valign: 'top'
        }
      },
      margin: { left: PDF_STYLES.margins.left, right: PDF_STYLES.margins.right },
      didDrawCell: (data: any) => {
        // Add subtle borders for better readability
        if (data.column.index === 0) {
          doc.setDrawColor(PDF_STYLES.colors.primary);
          doc.setLineWidth(0.2);
          doc.line(data.cell.x, data.cell.y, data.cell.x, data.cell.y + data.cell.height);
        }
      }
    });

    yPos = (doc as any).lastAutoTable.finalY + PDF_STYLES.spacing.sectionSpacing;
  }

  return yPos;
}

/**
 * Adds detailed note sections with intelligent page breaks.
 */
function addDetailedNoteSections(doc: jsPDF, note: MedicalNote, startY: number): number {
  let yPos = startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxY = pageHeight - PDF_STYLES.margins.bottom - 20; // Leave space for footer

  // Section heading
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(PDF_STYLES.sizes.heading1);
  doc.setTextColor(PDF_STYLES.colors.secondary);
  doc.text('DETAILED CLINICAL NOTE', PDF_STYLES.margins.left, yPos);
  yPos += PDF_STYLES.spacing.sectionSpacing;

  note.refinedNote.sections.forEach((section) => {
    // Check if we need a new page for the section
    const estimatedSectionHeight = 30 + (section.body.length / 80) * 4; // Rough estimate
    if (yPos + estimatedSectionHeight > maxY) {
      doc.addPage();
      yPos = PDF_STYLES.margins.top + 10;
    }

    // Section subheading
    doc.setFont(PDF_STYLES.fonts.heading, 'bold');
    doc.setFontSize(PDF_STYLES.sizes.heading2);
    doc.setTextColor(PDF_STYLES.colors.accent);
    doc.text(section.heading.toUpperCase(), PDF_STYLES.margins.left, yPos);
    yPos += 6;

    // Section content with text wrapping
    doc.setFont(PDF_STYLES.fonts.body, 'normal');
    doc.setFontSize(PDF_STYLES.sizes.body);
    doc.setTextColor(PDF_STYLES.colors.text);

    const textLines = doc.splitTextToSize(section.body, PAGE_CONFIG.usableWidth);
    
    // Check if content fits on current page
    const contentHeight = textLines.length * PDF_STYLES.spacing.lineHeight * PDF_STYLES.sizes.body / 3;
    if (yPos + contentHeight > maxY) {
      doc.addPage();
      yPos = PDF_STYLES.margins.top + 10;
      
      // Repeat section heading on new page
      doc.setFont(PDF_STYLES.fonts.heading, 'bold');
      doc.setFontSize(PDF_STYLES.sizes.heading2);
      doc.setTextColor(PDF_STYLES.colors.accent);
      doc.text(`${section.heading.toUpperCase()} (continued)`, PDF_STYLES.margins.left, yPos);
      yPos += 6;
      
      doc.setFont(PDF_STYLES.fonts.body, 'normal');
      doc.setFontSize(PDF_STYLES.sizes.body);
      doc.setTextColor(PDF_STYLES.colors.text);
    }

    textLines.forEach((line: string) => {
      if (yPos > maxY) {
        doc.addPage();
        yPos = PDF_STYLES.margins.top + 10;
      }
      doc.text(line, PDF_STYLES.margins.left, yPos);
      yPos += PDF_STYLES.spacing.lineHeight * PDF_STYLES.sizes.body / 3;
    });

    yPos += PDF_STYLES.spacing.sectionSpacing;
  });

  return yPos;
}

/**
 * Adds AI-generated summaries section.
 */
function addAISummariesSection(doc: jsPDF, note: MedicalNote, config: ExportConfig, startY: number): number {
  let yPos = startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxY = pageHeight - PDF_STYLES.margins.bottom - 20;

  const hasPatientSummary = config.includePatientSummary && note.patientSummary;
  const hasClinicalSummary = config.includeClinicalSummary && note.clinicalSummaryText;

  if (!hasPatientSummary && !hasClinicalSummary) {
    return yPos;
  }

  // Check if we need a new page
  if (yPos + 50 > maxY) {
    doc.addPage();
    yPos = PDF_STYLES.margins.top + 10;
  }

  // Section heading
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(PDF_STYLES.sizes.heading1);
  doc.setTextColor(PDF_STYLES.colors.secondary);
  doc.text('AI-GENERATED SUMMARIES', PDF_STYLES.margins.left, yPos);
  yPos += PDF_STYLES.spacing.sectionSpacing;

  // Patient summary
  if (hasPatientSummary && note.patientSummary) {
    doc.setFont(PDF_STYLES.fonts.heading, 'bold');
    doc.setFontSize(PDF_STYLES.sizes.heading2);
    doc.setTextColor(PDF_STYLES.colors.accent);
    doc.text('Patient-Friendly Summary', PDF_STYLES.margins.left, yPos);
    yPos += 6;

    doc.setFont(PDF_STYLES.fonts.body, 'normal');
    doc.setFontSize(PDF_STYLES.sizes.body);
    doc.setTextColor(PDF_STYLES.colors.text);

    const patientTextLines = doc.splitTextToSize(note.patientSummary, PAGE_CONFIG.usableWidth);
    patientTextLines.forEach((line: string) => {
      if (yPos > maxY) {
        doc.addPage();
        yPos = PDF_STYLES.margins.top + 10;
      }
      doc.text(line, PDF_STYLES.margins.left, yPos);
      yPos += PDF_STYLES.spacing.lineHeight * PDF_STYLES.sizes.body / 3;
    });

    yPos += PDF_STYLES.spacing.sectionSpacing;
  }

  // Clinical summary text
  if (hasClinicalSummary && note.clinicalSummaryText) {
    if (yPos + 30 > maxY) {
      doc.addPage();
      yPos = PDF_STYLES.margins.top + 10;
    }

    doc.setFont(PDF_STYLES.fonts.heading, 'bold');
    doc.setFontSize(PDF_STYLES.sizes.heading2);
    doc.setTextColor(PDF_STYLES.colors.accent);
    doc.text('Clinical Summary', PDF_STYLES.margins.left, yPos);
    yPos += 6;

    doc.setFont(PDF_STYLES.fonts.body, 'normal');
    doc.setFontSize(PDF_STYLES.sizes.body);
    doc.setTextColor(PDF_STYLES.colors.text);

    const clinicalTextLines = doc.splitTextToSize(note.clinicalSummaryText, PAGE_CONFIG.usableWidth);
    clinicalTextLines.forEach((line: string) => {
      if (yPos > maxY) {
        doc.addPage();
        yPos = PDF_STYLES.margins.top + 10;
      }
      doc.text(line, PDF_STYLES.margins.left, yPos);
      yPos += PDF_STYLES.spacing.lineHeight * PDF_STYLES.sizes.body / 3;
    });

    yPos += PDF_STYLES.spacing.sectionSpacing;
  }

  return yPos;
}

/**
 * Adds translation section if available.
 */
function addTranslationSection(doc: jsPDF, note: MedicalNote, startY: number): number {
  if (!note.translatedSummary || !note.targetLanguage) {
    return startY;
  }

  let yPos = startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxY = pageHeight - PDF_STYLES.margins.bottom - 20;

  // Check if we need a new page
  if (yPos + 50 > maxY) {
    doc.addPage();
    yPos = PDF_STYLES.margins.top + 10;
  }

  // Section heading
  doc.setFont(PDF_STYLES.fonts.heading, 'bold');
  doc.setFontSize(PDF_STYLES.sizes.heading1);
  doc.setTextColor(PDF_STYLES.colors.secondary);
  doc.text(`TRANSLATED SUMMARY (${note.targetLanguage.toUpperCase()})`, PDF_STYLES.margins.left, yPos);
  yPos += PDF_STYLES.spacing.sectionSpacing;

  // Translation content
  doc.setFont(PDF_STYLES.fonts.body, 'normal');
  doc.setFontSize(PDF_STYLES.sizes.body);
  doc.setTextColor(PDF_STYLES.colors.text);

  const translatedTextLines = doc.splitTextToSize(note.translatedSummary, PAGE_CONFIG.usableWidth);
  translatedTextLines.forEach((line: string) => {
    if (yPos > maxY) {
      doc.addPage();
      yPos = PDF_STYLES.margins.top + 10;
    }
    doc.text(line, PDF_STYLES.margins.left, yPos);
    yPos += PDF_STYLES.spacing.lineHeight * PDF_STYLES.sizes.body / 3;
  });

  return yPos + PDF_STYLES.spacing.sectionSpacing;
}

/**
 * Exports a medical note as a professional PDF document.
 * 
 * @param note - The medical note to export
 * @param config - Export configuration options
 * @param filename - The filename for the exported document
 */
export async function exportMedicalNotePDF(
  note: MedicalNote,
  config: ExportConfig,
  filename: string
): Promise<void> {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    let yPos = PDF_STYLES.margins.top;

    // Draw header
    if (config.includeHeader) {
      yPos = drawMedicalHeader(doc, config);
    }

    // Document title
    doc.setFont(PDF_STYLES.fonts.heading, 'bold');
    doc.setFontSize(PDF_STYLES.sizes.title);
    doc.setTextColor(PDF_STYLES.colors.primary);
    const title = `${note.encounterType || note.refinedNote.format} Clinical Note`;
    doc.text(title, doc.internal.pageSize.getWidth() / 2, yPos, { align: 'center' });
    yPos += 15;

    // Encounter information
    yPos = addEncounterInfoTable(doc, note, config, yPos);

    // Clinical summary
    yPos = addClinicalSummarySection(doc, note, yPos);

    // Detailed note sections
    yPos = addDetailedNoteSections(doc, note, yPos);

    // AI summaries
    yPos = addAISummariesSection(doc, note, config, yPos);

    // Translation section
    yPos = addTranslationSection(doc, note, yPos);

    // Add page numbers to all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      if (config.includeTimestamp) {
        drawFooter(doc, i, totalPages);
      }
    }

    // Save the PDF
    const pdfBlob = doc.output('blob');
    saveAs(pdfBlob, `${filename}.pdf`);

    console.log(`PDF export completed: ${filename}.pdf`);

  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error(`Failed to generate PDF document: ${(error as Error).message}`);
  }
}