/**
 * @fileoverview Medical note type definitions (legacy schema).
 * 
 * These types represent the original MedicalNote structure used throughout
 * the application. While new code should use MedicalNoteData from storage.ts,
 * these types are preserved for backward compatibility with existing UI and
 * export components.
 * 
 * @module shared/types/medical-note
 */

/**
 * Represents the format type of a clinical note.
 */
export type NoteFormat =
  | 'SOAP'
  | 'Progress'
  | 'Discharge'
  | 'Conference'
  | 'Consultation'
  | 'Procedure'
  | 'Unknown';

/**
 * Represents the role of a speaker detected in the medical transcript.
 */
export type SpeakerRole = 
  | 'Provider'
  | 'Patient'
  | 'Nurse'
  | 'Anesthesiologist'
  | 'Resident'
  | 'Student'
  | 'Technician'
  | 'Family'
  | 'Specialist'
  | 'Paramedic'
  | 'Other'
  | 'Unknown';

/**
 * Represents a single segment of transcribed speech with speaker identification.
 */
export interface TranscriptSegment {
  speaker: SpeakerRole;
  text: string;
}

/**
 * Represents a section of a structured medical note.
 */
export interface LegacyNoteSection {
  heading: string;
  body: string;
}

export type { LegacyNoteSection as NoteSection };

/**
 * Represents the refined, structured medical note with formatted sections.
 */
export interface RefinedNote {
  format: NoteFormat;
  sections: LegacyNoteSection[];
}

/**
 * Represents a concise clinical summary extracted from the medical note.
 */
export interface ClinicalSummary {
  chiefComplaint: string;
  keyFindings: string;
  plan: string;
  followUp: string;
}

/**
 * The complete medical note structure generated by the AI (legacy schema).
 */
export interface MedicalNote {
  id: string;
  timestamp: string;
  encounterType?: NoteFormat;
  rawTranscript: string;
  cleanedTranscript: string;
  labeledTranscript: TranscriptSegment[];
  refinedNote: RefinedNote;
  clinicalSummary: ClinicalSummary;
  
  // AI-enhanced summaries
  patientSummary?: string;
  clinicalSummaryText?: string;
  
  // Translation support
  translatedSummary?: string;
  targetLanguage?: string;
  
  // Processing metadata
  aiProcessingTime?: number;
}

